package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u211/12973/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, April 1, 2019 8:56:03 PM PDT
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
	 * The value representing ID_UNIQUENESS_POLICY_ID.
	 */
  public static final int value = (int)(18L);
}
